//https://stackoverflow.com/questions/8317508/hash-function-for-a-string
#include "List.h"
#include <array>
#include <cmath>
#include <iostream>

template <typename nodeType>
class HashNode
{
  public:
    std::string key; //stores the key of the hashnode. this helps to identify a hash index of a key in cases of collision
    LinkedList<nodeType> list; //value of the hashnode

    HashNode() //default constructor
    {
      this->key = "";
    }
    
    HashNode(std::string key) //parametrized constructor
    {
      this->key = key;
    }
};

template <typename nodeType>
class HashTable
{
  public:
    int totalBuckets;
    int currentSize;

    //an array of size totalBuckets that will store the hashed values
    HashNode<nodeType> *hashTable;

    HashTable(int buckets) //default constructor
    {
      if(buckets <= 0)
        buckets = 1;
      this->totalBuckets = buckets;
      currentSize = 0;
      hashTable = new HashNode<nodeType>[totalBuckets];
      //will need to change .fill to some other value as fill(-1) works for int keyType only
      //hashTable.fill(-1); //fills the entire array with -1 values
    }

    ~HashTable()
    {
      delete[] hashTable;
      hashTable = nullptr;
      totalBuckets = 0;
      currentSize = 0;
    }

    HashTable(const HashTable& other)
    {
      totalBuckets = other.totalBuckets;
      currentSize = other.currentSize;
      hashTable = new HashNode<nodeType>[totalBuckets];
      for(int i = 0; i < totalBuckets; i++)
      {
        hashTable[i] = other.hashTable[i];
      }
    }

    HashTable& operator=(const HashTable& other)
    {
      if(this == &other)
        return *this;

      HashNode<nodeType>* newTable = new HashNode<nodeType>[other.totalBuckets];
      for(int i = 0; i < other.totalBuckets; i++)
      {
        newTable[i] = other.hashTable[i];
      }

      delete[] hashTable;
      hashTable = newTable;
      totalBuckets = other.totalBuckets;
      currentSize = other.currentSize;
      return *this;
    }

    HashTable(HashTable&& other) noexcept
    {
      totalBuckets = other.totalBuckets;
      currentSize = other.currentSize;
      hashTable = other.hashTable;
      other.totalBuckets = 0;
      other.currentSize = 0;
      other.hashTable = nullptr;
    }

    HashTable& operator=(HashTable&& other) noexcept
    {
      if(this == &other)
        return *this;

      delete[] hashTable;
      totalBuckets = other.totalBuckets;
      currentSize = other.currentSize;
      hashTable = other.hashTable;
      other.totalBuckets = 0;
      other.currentSize = 0;
      other.hashTable = nullptr;
      return *this;
    }

    // hash function to map values to key
    int hashFunction(int x) {
      return (x % totalBuckets);
    }

    int hashFunction(std::string x)
    {
      int hash = 37;
      for(int i=0; i<x.size(); i++)
      {
        hash = (hash*54059) ^ (int(x[i]) * 76793);
      }
      return std::abs(hash % totalBuckets);
    }

    int probeStep(int hashIndex)
    {
      // Ensure probing always advances and cycles across the table.
      return 1 + (hashIndex % (totalBuckets - 1));
    }

    // void linearProbingInsert(keyType key) //inserts an item into the hash table at a particular index generated by the hash function
    // {
    //   int hashIndex = hashFunction(key);
      
    //   while (hashTable[hashIndex] != key && hashTable[hashIndex] != -1) 
    //   { //linearly probe through the list
    //     hashIndex++;
    //     hashIndex %= totalBuckets;
    //   }

    //   if(hashTable[hashIndex] == -1)
    //     currentSize++;
    //   hashTable[hashIndex] = key;
    // }

    // void quadraticProbingInsert(keyType key) //inserts an item into the hash table at a particular index generated by the hash function
    // {
    //   int hashIndex = hashFunction(key);
      
    //   if(hashTable[hashIndex] == -1)
    //     hashTable[hashIndex] = key;
    //   else
    //   {
    //     for(int i=1; i<totalBuckets; i++)
    //     {
    //       //calaculate new hash index by quadratic probing
    //       int newHashIndex = (hashIndex + i*i) % totalBuckets;

    //       if(hashTable[newHashIndex] == -1)
    //       {
    //         hashTable[newHashIndex] = key;
    //         break;
    //       }
    //     }
    //   }
    //   currentSize++;
    // }

    void doubleHashInsert(std::string key, nodeType value) //inserts an item into the hash table at a particular index generated by the hash function using double hash functionality
    {
      if(totalBuckets <= 0)
        return;

      int hashIndex = hashFunction(key);

      if( hashTable[hashIndex].key == key ) //if the key has an existing index
      {
        hashTable[hashIndex].list.insert(value); 
      }
      //else if index is unassigned, insert the data and save the key in the index 
      else if( hashTable[hashIndex].key == "" )
      {
        hashTable[hashIndex].list.insert(value);
        hashTable[hashIndex].key = key;
        currentSize++;
      }
      else if(hashTable[hashIndex].key != key && hashTable[hashIndex].key != "") //else if a collision has occurred, we must now either find its index if the key has been assigned one, or find the next empty index and assign it that
      {
        int newHashIndex;
        int step = 1;
        if(totalBuckets > 1)
          step = probeStep(hashIndex);

        for(int i=1; i<totalBuckets; i++) //bounded probing prevents infinite loops
        {
          newHashIndex = (hashIndex + i*step) % totalBuckets; //double hash probing
          if( hashTable[newHashIndex].key == key || hashTable[newHashIndex].key == "") 
          {
            hashTable[newHashIndex].list.insert(value);
            if(hashTable[newHashIndex].key == "")
            {
              hashTable[newHashIndex].key = key;
              currentSize++;
            }
            break;
          }
        }
      }
    };

    int getIndex(std::string key)
    {
      if(totalBuckets <= 0)
        return -1;

      int hashedIndex = hashFunction(key);

      if(hashTable[hashedIndex].key == key) //return the index if the key matches
        return hashedIndex;
      else if(hashTable[hashedIndex].key != "") //else if a collision has occurred, we must find the actual index (if it exists) 
      {
        int newHashIndex;
        int step = 1;
        if(totalBuckets > 1)
          step = probeStep(hashedIndex);

        for(int i=1; i<totalBuckets; i++) //loop to find the new index
        {
          newHashIndex = (hashedIndex + i*step) % totalBuckets;
          if( hashTable[newHashIndex].key == "" ) //however, if at any time an empty index is found, that means the key wasn't assigned any index to begin with, therefore -1 is returned
          {
            return -1;
          }
          else if( hashTable[newHashIndex].key == key ) {
            break;
          }
        }
        return newHashIndex;
      }
      return -1;
    }

    // void deleteItem(string key)
    // {
    //   // get the hash index of key
    //   int index = getIndex(key);

    //   // if key is found in hash hashTable, remove it
    //   if(hashTable[index] == key )
    //     hashTable[index] = -1;
      
    //   currentSize--;
    // }

    // function to display hashTable with index and its entries
    void displayHash() 
    {
      for (int i = 0; i < totalBuckets; i++) 
      {
        std::cout << "Index " << i << ": " << hashTable[i] << std::endl;
      }
      std::cout << std::endl;
    }
};